version: '3.1'

services:
  balancer:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - 3000:3000/tcp

  app:
    build:
      context: .
    restart: always
    env_file:
      .env
    depends_on:
      - redis

  fetcher:
    build:
      context: .
      dockerfile: Dockerfile.fetcher
    restart: always
    env_file:
      .env
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379/tcp
